/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/UI/Avatar.vue')['default']
    Banner: typeof import('./components/Main/Banner.vue')['default']
    Button: typeof import('./components/UI/Button.vue')['default']
    Header: typeof import('./components/Main/Header.vue')['default']
    MainHeader: typeof import('./components/Main/MainHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpForm: typeof import('./components/Main/SignUpForm.vue')['default']
    Subheader: typeof import('./components/Main/Subheader.vue')['default']
    UsersList: typeof import('./components/Main/UsersList.vue')['default']
  }
}
